/* Shared, English help content for the tools and the menu guide. */
const HM_HELP = {
  themes: {title:'Custom Themes',items:[['Create or edit','Open Appearance → Theme Editor. Select a standard template or saved theme, adjust the five colours and name, then choose Save & Apply. New Copy creates a separate theme. The automatically generated shades are shown in the preview.'],['Activate or delete','Activate Saved applies the stored theme without saving your edits. Delete is available only for custom themes. Deleting the active custom theme restores Ocean Blue. Settings are shared by this spreadsheet.'],['Readability','Light surfaces work best with existing layouts. Review the contrast hints and check your sheets after applying; the hints do not cover every chart and status combination. Reopen dialogs to load the active theme.']]},
  branding: {title:'Branding',items:[['Personalize your stud','Open Herd Management → Appearance → Branding. Set the stud name, signature, direct HTTPS logo image URL and optional dashboard subtitle. Preview your choices, then save.'],['Shared settings','Branding belongs to this spreadsheet and is shared by its users. Reopen the dashboard, dialogs and sidebar after saving.'],['Images and defaults','Use a public image URL rather than a sharing page. Restore Defaults saves the neutral Herd Tracker branding. A blank logo field uses the original logo; signature and subtitle may be empty.']]},
  import: {title:'Horse Import', items:[['Workflow','Paste the matching Horse Reality Info, Colour and Stats tabs, generate the preview, correct any extracted values, then select the export targets and choose Complete Import. Generating a preview does not save the horse.'],['Pasting','Use the original Horse Reality page layout. Extensions that rewrite the page can change the text the parser expects. Check the horse ID, breed, gender and stats in Review.'],['Export targets','Only the selected destinations are imported. Check existing records before completing an update. The HR Toolkit CSV input is an alternative source; the separate CSV Import tool is for structured sheet data.']]},
  outside: {title:'Outside Stud Import',items:[['Workflow','Paste the stallion data, review the extracted fields and complete the import. Check the breed and stud fees carefully.'],['Calculator eligibility','Outside studs need a breed to match the selected mare. A missing breed excludes the stud from matching and produces a warning. The maximum fee filter uses the HRC fee; it is not a combined HRC, DP and FT budget.']]},
  pedigree: {title:'Pedigree',items:[['Family tree','Select the horse and paste the Pedigree section from its Info tab. Extract the tree, check the names and correct missing or misplaced ancestors before saving.'],['Abbreviations','Sire means father; dam means mother. GS/GD are grandfather/grandmother; GGS/GGD are great-grandfather/great-grandmother. P. is the paternal branch and M. the maternal branch.'],['What the calculator knows','This tree stores three ancestral generations for each parent, giving four generations from a potential foal. An incomplete tree cannot rule out shared ancestors farther back.']]},
  scores: {title:'Add Scores',items:[['Results','Select a horse from the suggestions and choose the matching result type. Paste show results or competition results, then save. Existing duplicates for that horse are removed before saving.'],['Optional totals','DC means Day Champion. Premium and prize fields are achievement totals, not scores for an individual result. Leave a field blank to keep its existing value.'],['Clean duplicates','The separate clean-up action applies to all horses; it is broader than saving the selected horse.']]},
  csv: {title:'CSV Import',items:[['Choose a profile','Select the destination profile first. Paste CSV including its header row; column names must match fields recognized by that profile.'],['Import behaviour','Unknown columns are ignored. The importer fills empty target rows and preserves formula columns. Import writes to the sheet; check the chosen profile and source data before pressing it.']]},
  activity: {title:'Activity Import',items:[['Notifications or Bank Log','Use Notifications for messages and Bank Log for bank transactions. Paste directly from Horse Reality to preserve horse links and IDs.'],['Parse saves','Parse processes and writes recognized entries to Activity Log. It is not a preview. Clear only empties the input/results on screen; it does not undo imports.'],['Review and skipped entries','Uncertain entries are saved to Needs Review for manual checking, not automatically approved. Skipped entries include duplicates and deliberately ignored messages. Check errors before retrying. Use Tools & Maintenance → Show Log Tabs to find the logs.'],['Avoid duplicate sources','Importing the same event from differently formatted sources may not produce the same duplicate key. Avoid importing the same payment once from Notifications and again from Bank Log without checking Activity Log.']]},
  snapshot: {title:'Daily Snapshot',items:[['XP input','Enter the XP shown within your current level, not lifetime XP. Level and XP determine progress to the next level. Since Last includes XP across level-ups. Day Total compares against the last snapshot before today in the spreadsheet time zone, or the first snapshot today if no earlier one exists. Without a midnight snapshot it is an estimate, not an exact calendar-day measurement.'],['Balances and capacity','Enter current balances, not the amount gained today. Stalls Owned is total capacity; Horses on Pasture is the current count away on pasture. The dashboard subtracts that count from the herd total.'],['Save','Save records a new snapshot and updates the balance information. Interest figures are estimates based on the configured tiers; the monthly estimate is daily interest multiplied by 30.']]},
  tagline: {title:'Tagline Printer',items:[['Copy options','Select a horse from the suggestions. Copy Tagline copies only the generated tagline. Copy Name extracts the Stable Name line from Additional Info. Copy Complete Info copies all Additional Info text.'],['Settings','Reorder fields and choose which ones to include. Save Settings to retain your choices. Keep the Stable Name line enabled if you use Copy Name. These controls format the generated text; copying does not paste it into Horse Reality.']]},
  evaluation: {title:'Breeding Evaluation',items:[['Candidate and comparison group','Paste a candidate to compare it with the selected herd group. Without a candidate, the tool ranks the herd. Breed, gender and line filters define the comparison group.'],['Weights and scores','OFF ignores a metric; LOW, MED and HIGH increase its influence. Index Score is a weighted comparison against the group, not a Horse Reality score. Changing the group or weights can change ranks.'],['Goal Match','Goal Match expresses the configured breeding-goal fit, not a probability of a successful covering or a guaranteed foal quality. The optional colour target affects goal matching, not the herd index.'],['Replacement suggestion','The suggestion compares simplified herd-average scenarios. It does not sell a horse or include every factor in a breeding decision.']]},
  calculator: {title:'Foal Calculator',items:[['Selection and filters','Select a mare by name or ID. Candidates are same-breed adult stallions with usable stats. Minimum GP and conformation filters apply to estimates; predictions are not guaranteed foal results. Show next 15 reveals more matches.'],['HR-COI versus pedigree estimate','HR-COI is the official value you manually enter for this exact pairing. Max. HR-COI filters those recorded values; pairs without one remain visible. The separate four-generation pedigree estimate is not the official HR-COI. No recorded overlap does not prove the horses are unrelated.'],['Common ancestors','The list shows matches in the stored parent pedigrees. A known shared ancestor’s own COI can contribute to the local estimate. The parents’ individual COIs are not simply averaged.'],['Colours','Colour probabilities use the stored parental genetic codes and supported inheritance rules. Missing or unknown information limits the forecast. Expand Show all genotypes to inspect grouped outcomes.'],['Book Breeding','Booking records the pairing in your sheet. It does not perform a covering in Horse Reality. An existing booking is protected from being overwritten.']]},
  dashboard: {title:'Dashboard',items:[['Scope','The dashboard summarizes stored sheet data. Refresh reloads it; it does not fetch fresh horse profiles from Horse Reality. Some panels remain herd-wide, including account balances and stall capacity.'],['Comparisons','Adults vs Foals compares group averages with a separate scale for each metric. Missing measurements are excluded. Figures based on Activity Log can only include events you have imported.'],['Abbreviations','GP: genetic potential. VG: Very good conformation traits. Confo: conformation. Comp: competition. COI: coefficient of inbreeding. HRC, DP, FT and WT are the game currencies.'],['Themes','After changing the theme, close and reopen a tool to load its new colours. Imported names and user-entered text are displayed as stored.']]}
};
function hmHelpEscape_(text) { return String(text).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function hmHelpContent_(topic) { return topic.items.map(([title,text])=>'<section><h3>'+hmHelpEscape_(title)+'</h3><p>'+hmHelpEscape_(text)+'</p></section>').join(''); }
function hmHelpStyle_() { return '<style>.hm-help{font:14px/1.55 Finlandica,Arial,sans-serif;color:var(--primary-deep);margin:16px;padding:12px 16px;background:var(--neutrals-white);border:1px solid var(--secondary-base);border-radius:10px;letter-spacing:normal;text-transform:none}.hm-help summary{cursor:pointer;font:600 14px/1.5 Finlandica,Arial,sans-serif;color:var(--primary-dark);display:list-item;list-style:disclosure-closed}.hm-help[open]>summary{list-style:disclosure-open}.hm-help summary::before{content:none}.hm-help summary:focus-visible{outline:2px solid var(--secondary-base);outline-offset:4px}.hm-help h3{font:600 15px/1.4 Finlandica,Arial,sans-serif;margin:16px 0 4px;color:var(--primary-dark);letter-spacing:normal;text-transform:none}.hm-help p{margin:0 0 8px;font:14px/1.55 Finlandica,Arial,sans-serif}.hm-help-note{font:12px/1.5 Finlandica,Arial,sans-serif;color:var(--primary-mid);margin:8px 0 12px}.hm-guide{max-width:800px;margin:auto}.hm-guide h1{font:600 24px Finlandica,Arial,sans-serif;color:var(--secondary-base);background:var(--primary-dark);padding:24px;border-radius:12px}.hm-guide>p{font:14px/1.5 Finlandica,Arial,sans-serif;margin:16px}.hm-guide button{font:600 14px Finlandica,Arial,sans-serif;border:1px solid var(--secondary-base);background:var(--primary-dark);color:var(--neutrals-white);padding:10px 24px;border-radius:8px;cursor:pointer}</style>'; }
function renderModalHelp(key) { const topic=HM_HELP[key]; if(!topic)return ''; return hmHelpStyle_()+'<details class="hm-help"><summary>Help · '+hmHelpEscape_(topic.title)+'</summary>'+hmHelpContent_(topic)+'</details>'; }
function showHelpGuide() {
  const topics=Object.values(HM_HELP).map(t=>'<details class="hm-help"><summary>'+hmHelpEscape_(t.title)+'</summary>'+hmHelpContent_(t)+'</details>').join('');
  const html='<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><link href="https://fonts.googleapis.com/css2?family=Finlandica:wght@400;600&display=swap" rel="stylesheet">'+renderThemeVariables()+hmHelpStyle_()+'</head><body style="background:var(--primary-ultramuted);padding:16px"><main class="hm-guide"><h1>Help &amp; Guide</h1><p>Choose a tool below. Each tool also has its own expandable Help section at the bottom.</p>'+topics+'<button onclick="google.script.host.close()">Close</button></main></body></html>';
  SpreadsheetApp.getUi().showModalDialog(HtmlService.createHtmlOutput(html).setWidth(850).setHeight(750),'Help & Guide');
}
